export const ADD_PLACE = "ADD_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";

export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CLOSE_LOGIN_ERROR = "CLOSE_LOGIN_ERROR";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const SIGNIN_EMAIL_CHANGED = 'SIGNIN_EMAIL_CHANGED';
export const SIGNIN_PASSWORD_CHANGED = 'SIGNIN_PASSWORD_CHANGED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN = 'SIGNIN';
export const SIGNIN_CLEARDOWN = 'SIGNIN_CLEARDOWN';

export const SHOW_MESSAGE = "SHOW_MESSAGE";
