export const ADD_PLACE = "ADD_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";

export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CLOSE_LOGIN_ERROR = "CLOSE_LOGIN_ERROR";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const GET_ALL_PROFESSORS = "GET_ALL_PROFESSORS";
export const ADD_REVIEW_FOR_PROFESSOR = "ADD_REVIEW_FOR_PROFESSOR";
export const CHANGED_CURRENT_PROFESSOR = "CHANGED_CURRENT_PROFESSOR";
export const GET_ATTENDANCES_FOR_STUDENT = "GET_ATTENDANCES_FOR_STUDENT";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const SET_ATTENDANCE_INFO_ID = "SET_ATTENDANCE_INFO_ID";
export const SAVE_ATTENDANCE_INFO_DATA = "SAVE_ATTENDANCE_INFO_DATA";


export const SHOW_MESSAGE = "SHOW_MESSAGE";
